config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'market#index'
  resources :market, as: :categorys
  resources :products
  devise_for :users
  get '/seller/:id', to: 'market#seller', as: 'seller'
  get '/usercenter', to: 'usercenter#index'
  get '/wishlist', to: 'usercenter#wishlist', as: 'wishlist'
  delete '/wishlist/:item', to: 'usercenter#delete_wishlist', as: 'destroy_wishlist'
  post '/wishlist/:item', to:'usercenter#create_wishlist', as: 'create_wishlist'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :wishlists, dependent: :destroy
  has_many :users, through: :wishlists
  has_one_attached :picture
  
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :wishlists, dependent: :destroy
  has_many :wishlist_products, class_name: "Product", through: :wishlists, source: :product
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of     :name
  validates_presence_of     :phone
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone])
  end

  $categories = Category.order(:name)

end

app/controllers/market_controller.rb
class MarketController < ApplicationController
    def index
        @categories = Category.order(:name)
        @products = Product.order(created_at: :desc).limit(8)
    end

    def show
        @category = Category.find(params[:id])
        @products = @category.products
    end

    def seller
        @seller = User.find(params[:id])
        @products = @seller.products
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!, only: %i[new]
  before_action :set_item, only: %i[show update edit destroy]
  before_action :find_categories, only: %i[new create edit update]

  def show
    if user_signed_in?
      @already_in_wishlist = current_user.wishlist_products.include? @product
    else
      @already_in_wishlist = false
    end
  end

  def new 
    @product = Product.new
  end

  def create
    @product = Product.new

    @item = Product.new(item_params)
    if @item.save
      redirect_to product_path(@item.id)
    else
      flash.now[:errors] = @item.errors.full_messages
      render action: 'new'
    end
  end

  def edit; end

  def update
    @product.update(item_params)
    redirect_to product_path(@product.id)
  end

  def destroy
    if @product
      @product.destroy
      redirect_to usercenter_path
    end
  end

  def item_params
    params.require(:product).permit(:name, :price, :category_id, :user_id, :description, :picture)
  end

  def set_item
    @product = Product.find(params[:id])
  end

  def find_categories
    @categories = Category.order(:name)
  end
end

app/controllers/usercenter_controller.rb
class UsercenterController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user

    def index
        @products = @user.products
        @owner = true
    end

    def wishlist
        @products = @user.wishlist_products
        @owner = false
    end

    def delete_wishlist
        @item = Product.find(params[:item])
        @user.wishlist_products.delete(@item)
        redirect_to wishlist_path
    end

    def create_wishlist
        @item = Product.find(params[:item])
        @user.wishlist_products << @item
        redirect_to wishlist_path
    end

    def set_user
        @user = User.find(current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/market_helper.rb
module MarketHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/usercenter_helper.rb
module UsercenterHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PC Mart</title>
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&family=Roboto&display=swap"
      rel="stylesheet"
    />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# Header %>
    <div class="header">
      <div class="container">
        <div class="logo"><%= link_to "PC Mart", root_path() %></div>
        <div class="menu">
          <div><%= link_to "Create Listing", new_product_path(), class: "create" %></div>
          <div>
            <% if user_signed_in? %>
              <%= link_to "My Account", usercenter_path() %>
            <% else %>
              <%= link_to "Login", new_user_session_path() %> |
              <%= link_to "Register", new_user_registration_path() %> 
            <% end %>
          </div>
          <div><%= link_to "Wish List", wishlist_path(), class: "wishlist" %></div>
        </div>
      </div>
    </div>

    <div class="container main">
      <% if notice %>
        <p class="notice"><%= notice %></p> 
      <% end %>
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <% if flash[:errors] %>
        <ul class="alert">
          <% flash[:errors].each do |error| %>
            <li><%= " #{error}," %></li>
          <% end %>
        </ul>
      <% end %>
      <%= yield %>
    </div>

    <div class="footer">
      <div class="container">
        <div class="logo"><%= link_to "PC Mart", root_path() %></div>
        <div class="menu">
          <div class="title">Account</div>
          <%= link_to "Login", new_user_session_path() %>
          <%= link_to "Register", new_user_registration_path() %> 
          <%= link_to "My Account", usercenter_path() %>
          <%= link_to "Edit my details", edit_user_registration_path() %>
          <%= link_to "Logout", destroy_user_session_path(), method: :delete %>
        </div>
        <div class="menu">
          <div class="title">Listings</div>
          <%= link_to "Create Listing", new_product_path() %>
          <%= link_to "Manage my listings", usercenter_path() %>
          <%= link_to "My Wishlist", wishlist_path() %>
        </div>
        <div class="menu">
          <div class="title">Categories</div>
          <% $categories.each do | category | %>
            <%= link_to category.name, category_path(category.id) %>
          <% end %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/market/_products.html.erb
<% if !@products.any? %>
  <div class="no_product">
    <%= image_tag("sad.png", width: 250) %>
    <p>There are no products yet</p>
  </div>
<% else %>
  <div class="box">
    <% @products.each do | product | %>
      <div class="product_card">
        <div>
          <a href="<%= product_path(product.id) %>">
            <% if product.picture.attached? %> 
              <%= cl_image_tag product.picture.key, crop: :scale, width: 180, cloud_name: 'dkh1bbave'%> 
            <% elsif product.default_image?  %> 
              <%= image_tag("#{product.default_image}.jpg", width: 180) %>
            <% end %>
          </a>
        </div>
        <div>
          <a href="<%= product_path(product.id) %>">
            <p class="name"> <%= product.name %> </p>
            <p class="price">$<%= product.price%></p>
          </a>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/market/index.html.erb
<div class="market">
  <h2>Browse our categories</h2>
  <div class="box first">
    <% @categories.each do | category | %>
    <div class="card">
      <div>
        <a href="<%= category_path(category.id) %>">
          <%= image_tag("#{category.name}.jpg", width: 150) %>
        </a>
      </div>
      <div>
        <a href="<%= category_path(category.id) %>"> <%= category.name %> </a>
      </div>
    </div>
    <% end %>
  </div>

  <h2>New Listings</h2>
  <%= render 'products' %>
</div>

app/views/market/seller.html.erb
<div class="market seller">
  <h1><%= @seller.name %></h1>
  <% if user_signed_in? %>
    <p>Email: <%= @seller.email %></p>
    <p>Phone: <%= @seller.phone %></p>
  <% else %>
    <%= button_to "Login to see contact details", new_user_session_path(), method: :get , class: "button red" %>
  <% end %>

  <h2>Current Listings by <%= @seller.name %></h2>
  <%= render 'products' %>
</div>

app/views/market/show.html.erb
<h2><%= @category.name %></h2>
<div class="market">
  <%= render 'products' %>
</div>

app/views/products/_form.html.erb
<%= form_with model: @product do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label "category" %><br />
    <%= f.collection_select :category_id, @categories, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    $<%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label "Upload product image" %><br />
    <%= f.file_field :picture %><br/>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit "Save", :class => 'button blue'  %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="new_listing">
  <h2>Edit Listing</h2>

  <%= render 'form' %>

</div>

app/views/products/new.html.erb
<div class="new_listing">
  <h2>Add New Listing</h2>

  <%= render 'form' %>

</div>

app/views/products/show.html.erb
<div class="product">
    <div class="product_info">
        <h2><%= @product.name %></h2>
        <% if @product.picture.attached? %>
            <p><%= cl_image_tag @product.picture.key, crop: :scale, width: 500, cloud_name: 'dkh1bbave' %></p>
        <% elsif @product.default_image? %>
           <p><%= image_tag("#{@product.default_image}.jpg", width: 500) %></p>
        <% end %>
        <h2>Price: $<%= @product.price %></h2>
        <h4>Category: <%= link_to @product.category.name, category_path(@product.category.id) %></h4>
        <h4>Product description: </h4>
        <p class="description"><%= @product.description %></p>
    </div>
    <div class="right_panel">
        <div class="seller_info">
            <h2>Seller Info</h2>
            <p><%= link_to @product.user.name, seller_path(@product.user.id) %></p>
            <% if user_signed_in? %>
                <p>Email: <%= @product.user.email %></p>
                <p>Phone: <%= @product.user.phone %></p>
            <% else %>  
                <%= button_to "Login to see contact details", new_user_session_path(), method: :get, class: "button red" %>
            <% end %>
        </div>
        <% if user_signed_in? && current_user == @product.user %>
            <%= button_to "Edit Listing", edit_product_path(@product), method: :get, class: "button red" %>
        <% elsif @already_in_wishlist %>
            <div class="button disabled">Saved in wishlist</div>
        <% elsif user_signed_in? %>
            <%= button_to "Save to wish list", create_wishlist_path(@product), method: :post, class: "button red" %>
        <% end %>
    </div>
</div>

app/views/usercenter/_listing.erb
<% if !@products.any? %>
  <div class="no_product">
    <%= image_tag("sad.png", width: 250) %>
    <p>No listings here yet</p>
  </div>
<% else %>
  <div class="product_list">
    <div class="product header_row">
      <div class="image">Image</div>
      <div class="name">Title</div>
      <div class="price">Price</div>
      <div class="manage">Manage</div>
    </div>
    <% @products.each do | product | %>
      <div class="product">
        <div class="image">
          <% if product.picture.attached? %> 
            <%= cl_image_tag product.picture.key, crop: :scale, width: 150, cloud_name: 'dkh1bbave'%>
          <% elsif product.default_image? %> 
            <%= image_tag("#{product.default_image}.jpg", width: 150) %>
          <% end %>
        </div>
        <div class="name">
          <a href="<%= product_path(product.id) %>">
            <%= product.name %>
          </a>
        </div>
        <div class="price">
          $<%= product.price%>
        </div>
        <div class="manage">
          <%= link_to "edit", edit_product_path(product), class: "edit" if @owner %>
          <%= " | " if @owner %>
          <%= link_to 'delete', @owner ? product_path(product) : destroy_wishlist_path(product), method: :delete, data: { confirm: "are you sure?"}, class: "delete" %><br />
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/usercenter/index.html.erb
 <div class="usercenter">
  <h1><%= current_user.name %></h1>
  <p>Email: <%= current_user.email %></p>
  <p>Phone: <%= current_user.phone %></p>
  <div class="action">
    <%= button_to "Edit my details", edit_user_registration_path(), method: :get, class: "button blue edit_details" %>
    <%= link_to "logout", destroy_user_session_path(), method: :delete, class: "logout" %>
  </div>
  <h2>Your current Listings: </h2>
  <%= render 'listing' %>
</div>

app/views/usercenter/wishlist.html.erb
 <div class="usercenter">
  <h2>Your Wishlist: </h2>
  <%= render 'listing' %>
</div>